upgraded to x11vnc 0.8.3
git-svn-id: https://italc.svn.sourceforge.net/svnroot/italc@8 d6290f70-d918-0410-89a7-c2321b9b1c3d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1336,6 +1336,7 @@ Optional Packages:
   --without-fbpm          disable fbpm extension support
   --without-v4l           disable video4linux support
   --without-fbdev         disable linux fb device support
+  --without-uinput        disable linux uinput device support
   --without-crypt         disable support for libcrypt
   --without-pthread       disable support for libpthread
 
@@ -6552,6 +6553,12 @@ echo "${ECHO_T}$QT_LDADD" >&6; }
 
 
 
+
+
+
+
+
+
 # Check whether --with-xkeyboard was given.
 if test "${with_xkeyboard+set}" = set; then
   withval=$with_xkeyboard;
@@ -6612,7 +6619,15 @@ if test "${with_fbdev+set}" = set; then
 fi
 
 
-if test "$X_CFLAGS" != "-DX_DISPLAY_MISSING"; then
+# Check whether --with-uinput was given.
+if test "${with_uinput+set}" = set; then
+  withval=$with_uinput;
+fi
+
+
+if test "x$with_x" = "xno"; then
+	HAVE_X="false"
+elif test "$X_CFLAGS" != "-DX_DISPLAY_MISSING"; then
 	{ echo "$as_me:$LINENO: checking for XGetImage in -lX11" >&5
 echo $ECHO_N "checking for XGetImage in -lX11... $ECHO_C" >&6; }
 if test "${ac_cv_lib_X11_XGetImage+set}" = set; then
@@ -6691,7 +6706,10 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_X11_XGetImage" >&5
 echo "${ECHO_T}$ac_cv_lib_X11_XGetImage" >&6; }
 if test $ac_cv_lib_X11_XGetImage = yes; then
-  HAVE_X="true"
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_X11 1
+_ACEOF
+ HAVE_X="true"
 else
   HAVE_X="false"
 fi
@@ -8971,6 +8989,241 @@ fi
 
 		fi
 
+		if test "x$with_uinput" != "xno"; then
+			if test "${ac_cv_header_linux_input_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for linux/input.h" >&5
+echo $ECHO_N "checking for linux/input.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_linux_input_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_linux_input_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_input_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking linux/input.h usability" >&5
+echo $ECHO_N "checking linux/input.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <linux/input.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking linux/input.h presence" >&5
+echo $ECHO_N "checking linux/input.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <linux/input.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: linux/input.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: linux/input.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/input.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: linux/input.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: linux/input.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: linux/input.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/input.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: linux/input.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/input.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: linux/input.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/input.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: linux/input.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/input.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: linux/input.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/input.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: linux/input.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ---------------------------------------------- ##
+## Report this to tobydox/at/users/dot/sf/dot/net ##
+## ---------------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for linux/input.h" >&5
+echo $ECHO_N "checking for linux/input.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_linux_input_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_linux_input_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_linux_input_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_input_h" >&6; }
+
+fi
+if test $ac_cv_header_linux_input_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_LINUX_INPUT_H 1
+_ACEOF
+ HAVE_LINUX_INPUT_H="true"
+fi
+
+
+			if test "x$HAVE_LINUX_INPUT_H" = "xtrue"; then
+				{ echo "$as_me:$LINENO: checking for linux/uinput.h" >&5
+echo $ECHO_N "checking for linux/uinput.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_linux_uinput_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <linux/input.h>
+
+#include <linux/uinput.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_linux_uinput_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_header_linux_uinput_h=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_linux_uinput_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_uinput_h" >&6; }
+if test $ac_cv_header_linux_uinput_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_LINUX_UINPUT_H 1
+_ACEOF
+
+fi
+
+
+			fi
+		fi
 		X_LIBS="$X_LIBS $X_PRELIBS -lX11 $X_EXTRA_LIBS"
 	fi
 fi
@@ -14921,7 +15174,8 @@ fi
 
 
 
-for ac_func in ftime mkfifo dup2 floor gethostbyname gethostname gettimeofday inet_ntoa memmove memset mmap pow putenv select socket strchr strdup strerror strpbrk strrchr strstr uname setsid getpwuid getpwnam getuid geteuid waitpid setutxent setpgrp seteuid grantpt
+
+for ac_func in ftime mkfifo dup2 floor gethostbyname gethostname gettimeofday inet_ntoa memmove memset mmap pow putenv select socket strchr strdup strerror strpbrk strrchr strstr uname setsid getpwuid getpwnam getuid geteuid waitpid setutxent setpgrp seteuid grantpt getspnam
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -15325,6 +15579,11 @@ _ACEOF
     ;;
 esac
 
+uname_s=`(uname -s) 2>/dev/null`
+if test "x$uname_s" = "xHP-UX"; then
+	# need -lsec for getspnam()
+	LDFLAGS="$LDFLAGS -lsec"
+fi
 
 # Check for rpm SOURCES path
 echo -n "checking for rpm sources path... "
